export const ITINERARY_TYPES = {
  PACKAGE: "PACKAGE",
  CUSTOM: "CUSTOM",
} as const;

export const MESSAGE_TYPES = {
  CANCELLATION_REQUEST: "CANCELLATION_REQUEST",
  REBOOKING_REQUEST: "REBOOKING_REQUEST",
  GENERAL_INQUIRY: "GENERAL_INQUIRY",
} as const;

export const PAYMENT_STATUS = {
  FULLY_PAID: "FULLY PAID",
  PARTIALLY_PAID: "PARTIALLY PAID",
  NOT_PAID: "NOT PAID",
} as const;

export const ORDER_STATUS = {
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  IN_MODIFICATION: "IN_MODIFICAITON",
  PENDING: "PENDING",
} as const;

export const PAYMENT_METHOD = {
  CASH: "CASH",
  GCASH: "GCASH",
  PENDING: "PENDING",
} as const;
