export const ITINERARY_TYPES = {
  PACKAGE: "PACKAGE",
  CUSTOM: "CUSTOM",
} as const;

export const MESSAGE_TYPES = {
  CANCELLATION_REQUEST: "CANCELLATION_REQUEST",
  REBOOKING_REQUEST: "REBOOKING_REQUEST",
  GENERAL_INQUIRY: "GENERAL_INQUIRY",
} as const;
